sudo: required
language: node_js

node_js:
  - "6"     # legacy
  - "8"     # maintenance
  - "lts/*" # LTS
  - "node"  # latest

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - PGUSER=postgres
    - PGHOST=localhost
  matrix:
    - POSTGRESQL_VERSION=9.5
    - POSTGRESQL_VERSION=9.6
    - POSTGRESQL_VERSION=10
    - POSTGRESQL_VERSION=11


before_install:
  - bash test/install-postgres-on-travis.sh

before_script:
  - psql -c 'CREATE DATABASE travis_db;'
  - export PGDATABASE=travis_db

cache:
  directories:
  - node_modules

branches:
  only:
    - master
