test:
  build: ./
  volumes:
    - .:/app
  working_dir: /app
  command: node_modules/mocha/bin/mocha --harmony test/setup.js test/**/*.js
  links:
    - db

db:
  image: postgres:9.5
  ports:
    - 5432:5432
