node:
  image: mhart/alpine-node:6.5.0
  volumes:
    - .:/app
  working_dir: /app

npm:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
    http_proxy: ${http_proxy}
  entrypoint: ['npm']

test:
  extends:
    file: ./docker-compose.yml
    service: node
  volumes:
    - .:/app
  working_dir: /app
  command: npm run test
  links:
    - db
  environment:
    - PGHOST=db
    - PGDATABASE=postgres
    - PGUSER=postgres
    - PGPASSWORD=postgres

db:
  image: postgres:9.5
