node:
  image: node:4.1.2
  volumes:
    - .:/app
  working_dir: /app

npm:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
    http_proxy: ${http_proxy}
  entrypoint: ['npm']

test:
  extends:
    file: ./docker-compose.yml
    service: node
  volumes:
    - .:/app
  working_dir: /app
  command: node_modules/mocha/bin/mocha --harmony test/setup.js test/**/*.js
  links:
    - db

db:
  image: postgres:9.5
