import updateOneQuerier from '../queries/updateOne';

export default function (tableName, fields, idFieldName, idAutoGenerated, returningFields) {

    const updateOneQuery = updateOneQuerier(tableName, fields, idFieldName, idAutoGenerated, returningFields);

    return function (client) {
        return function* updateOne(id, data) {

            const entity = (yield client.query(updateOneQuery(id, data)))[0];
            if (!entity) {
                throw new Error('not found');
            }

            return entity;
        };
    };
};
