'use strict';

module.exports = function (exposedFields, idAutoGenerated, idFieldName) {
    return function getValueSubQuery(data, suffix, isWhitelisted, raw) {
        suffix = suffix || '';
        var query = [];
        var parameters = {};
        var columns = [];

        var fields = (isWhitelisted ? Object.keys(data) : exposedFields);

        fields.forEach(function (field) {
            if (!raw && idAutoGenerated && field === idFieldName) return;
            if (!raw && typeof data[field] === 'undefined') return;
            columns.push(field);
            query.push('$' + field + suffix);
            parameters[field + suffix] = data[field];
        });

        return {
            query: query.join(', '),
            parameters: parameters,
            columns: columns
        };
    };
};
